# Learn more at http://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    patch: true
    changes: false

    project:
      target: 50%

    patch:
      target: 0%

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
