sudo: false
language: cpp
compiler:
  - gcc
  #- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - gcc-5
    - g++-5
    - clang-3.7
    - clang-format-3.7
    - clang-modernize-3.7
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - libboost1.55-all-dev
    - python-pip
    - libtbb-dev
    - ccache
    - libparmetis-dev
    - libsuitesparse-dev
    - lcov
    - curl

before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - cd $HOME
  - test -d src || git clone --branch=travis http://users.dune-project.org/repositories/projects/dune-stuff-demos.git src
  - cd $HOME/src
  - git submodule update --init --recursive
  - cp config.opts/travis $HOME/travis.opts && export DCONTROL_ARG="--opts=--builddir=${DUNE_BUILD_DIR} ${HOME}/travis.opts"
  - echo removing modules ${MODULES_TO_DELETE}
  # ensures dune-stuff from travis own checkout is used
  - rm -rf ${MODULES_TO_DELETE} dune-stuff
  # install Eigen
  - mkdir -p ${DUNE_BUILD_DIR}/eigen/build
  - wget -qO- http://bitbucket.org/eigen/eigen/get/3.2.4.tar.gz | tar xvz -C ${DUNE_BUILD_DIR}/eigen --strip-components=1
  - cd ${DUNE_BUILD_DIR}/eigen/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
  - make install
  # workarounds for dune-testtools issue
  - cd $HOME/src
  - ./dune-common/bin/dunecontrol ${DCONTROL_ARG} --module=dune-python configure
  - ${DUNE_BUILD_DIR}/dune-python/python2-env/bin/pip install -U pip
  - ${DUNE_BUILD_DIR}/dune-python/python3-env/bin/pip install -U pip
  - ${DUNE_BUILD_DIR}/dune-python/python2-env/bin/pip install -U distribute six
  - ${DUNE_BUILD_DIR}/dune-python/python3-env/bin/pip install -U distribute six

# command to install dependencies
install:
  - cd $HOME/src
    - pip install --user cpp-coveralls
  - ./dune-common/bin/dunecontrol ${DCONTROL_ARG} all
  - ./dune-common/bin/dunecontrol ${DCONTROL_ARG} make install > /dev/null
  - rm -rf ~/{dune_build,src}

# # command to run tests
script:
    - cd ${TRAVIS_BUILD_DIR}
    - ~/dune/bin/dunecontrol ${DCONTROL_ARG} --only=dune-stuff configure
    - ~/dune/bin/dunecontrol ${DCONTROL_ARG} --only=dune-stuff bexec ctest --output-on-failure -S ${TRAVIS_BUILD_DIR}/.travis.ctest
    - ~/dune/bin/dunecontrol ${DCONTROL_ARG} --only=dune-stuff bexec make headercheck -k

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/dune
    - $HOME/.ccache

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - os: osx

env:
  global:
    - DUNE_BUILD_DIR=${HOME}/dune_build/ INSTALL_DIR=$HOME/dune
  #matrix:
    #- MODULES_TO_DELETE="dune-fem dune-pdelab dune-typetree dune-grid dune-istl dune-testtools"
    #- MODULES_TO_DELETE="dune-fem dune-pdelab dune-typetree"
    #- USE_ALL_MODULES_IN_SUPER_REPO
