# This file is part of the dune-xt-la project:
#   https://github.com/dune-community/dune-xt-la
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2015 - 2016)
#   Rene Milk       (2015 - 2016)
#   Tobias Leibner  (2015)

sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources: &commonsources
    packages: &commonpackages
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - libboost1.55-all-dev
    - python-pip
    - libtbb-dev
    - ccache
    - libsuitesparse-dev
    - lcov
    - curl
    - ninja-build
    - python3-requests

before_install:
  - |-
    : ${OPTS:="config.opts/travis.ninja"} && export OPTS
  - |-
    : ${BUILD_CMD:="ninja -k 10000 -j 2"} && export BUILD_CMD
  # workaround for https://github.com/travis-ci/travis-ci/issues/5285
  - sudo -E apt-get install -y -q python-pip python3-pip
  - sudo -E pip3 install -U requests virtualenv cpp-coveralls
  - sudo -E pip install -U requests virtualenv cpp-coveralls
  - export PATH=/usr/lib/ccache:$PATH
  - cd $HOME
  - test -d src || git clone https://github.com/dune-community/dune-xt-super.git src
  - cd $HOME/src
  - pushd .travis ; ./init_sshkey.sh ${encrypted_862ca47045d1_key} ${encrypted_862ca47045d1_iv} ; popd
  - git submodule update --init --recursive
  - git submodule status
  - export DCTRL_ARG="--builddir=${DUNE_BUILD_DIR}  --opts=${OPTS}"
  # our local scripts look for an OPTS env entry
  - ./local/bin/download_external_libraries.py
  - ./local/bin/build_external_libraries.py
  # ensures ${MY_MODULE} from travis own checkout is used
  - echo removing modules ${MODULES_TO_DELETE}
  - rm -rf ${MODULES_TO_DELETE} ${MY_MODULE}

# command to install dependencies
install:
  - cd $HOME/src
  #- export INST_DCTRL=$HOME/dune/bin/dunecontrol
  - export SRC_DCTRL=$PWD/dune-common/bin/dunecontrol
  - ${SRC_DCTRL} ${DCTRL_ARG} all
  # move my travis checkout into this source tree
  - cp -ra ${TRAVIS_BUILD_DIR} .

before_script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} configure
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD}
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} test_binaries

script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} test
    # retry this step becuase of the implicated race condition in cloning an pushing with multiple builder running in parallel
    - travis_retry $HOME/src/scripts/bash/travis_upload_test_logs.bash ${DUNE_BUILD_DIR}/${MY_MODULE}/dune/xt/*/test/

    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} headercheck
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} install | grep -v "Installing"
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} package_source

# runs independent of 'script' failure/success
after_script:
    - |
     if [ "x${CLANG_FORMAT}" != "x" ] ; then
        git config --global hooks.clangformat ${CLANG_FORMAT}
        PYTHONPATH=$HOME/src/scripts/python/ python3 -c "import travis_report as tp; tp.clang_format_status(\"${TRAVIS_BUILD_DIR}\")"
     fi
    - |
      if [[ $TRAVIS_JOB_NUMBER == *.1 ]] ; then
        ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} doc
        ./.travis/init_sshkey.sh $encrypted_862ca47045d1_key $encrypted_862ca47045d1_iv dune-community.github.io
        ./.travis/deploy_docs.sh ${MY_MODULE} ${DUNE_BUILD_DIR}
      fi
    # reset for ctest
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec make clean
    - export CTEST_ARG="--output-on-failure -S ${TRAVIS_BUILD_DIR}/.travis.ctest"
    # ctest errors on coverage gathering, this should NOT fail our entire build
    #- ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ctest ${CTEST_ARG} || echo "CTest Failed"

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - MY_MODULE=dune-xt-la 
    - DUNE_BUILD_DIR=${HOME}/dune_build/ 
    - INSTALL_DIR=$HOME/dune 
    - CTEST_OUTPUT_ON_FAILURE=1

matrix:
  include:
    - os: linux
      addons: &gcc49
        apt:
          sources:
          - *commonsources
          - 'ubuntu-toolchain-r-test'
          packages:
          - *commonpackages
          - ['g++-4.9', 'gcc-4.9']
      env: CXX=g++-4.9 CC=gcc-4.9 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions"
    - os: linux
      addons: *gcc49
      env: CXX=g++-4.9 CC=gcc-4.9 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions dune-fem dune-pdelab dune-typetree dune-grid dune-istl"
    - os: linux
      addons: *gcc49
      env: CXX=g++-4.9 CC=gcc-4.9 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions dune-fem dune-pdelab"

    - os: linux
      addons:
        apt:
          sources:
          - *commonsources
          - 'ubuntu-toolchain-r-test'
          packages:
          - *commonpackages
          - ['g++-5', 'gcc-5']
      env: CXX=g++-5 CC=gcc-5 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions"

    - os: linux
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7', 'clang-format-3.7']
      env: CXX=clang++-3.7 CC=clang-3.7 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions" CLANG_FORMAT="/usr/bin/clang-format-3.7"

    - os: linux
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7']
      # fake last module to delete to distinguish testlogs
      env: OPTS=config.opts/travis.make BUILD_CMD="make -k -j2" CXX=clang++-3.7 CC=clang-3.7 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions with-make"

    #- os: linux
      #addons:
        #apt:
          #sources:
          #- *commonsources
          #- ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          #packages:
          #- *commonpackages
          #- ['clang-3.8']
      #env: CXX=clang++-3.8 CC=clang-3.8 MODULES_TO_DELETE="dune-xt-grid dune-xt-functions"
