sudo: false
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.7
    - clang-format-3.7
    - clang-modernize-3.7
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - libboost1.55-all-dev
    - python-pip
    - libtbb-dev
    - ccache

before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - cd $HOME
  - test -d src || git clone --branch=travis http://users.dune-project.org/repositories/projects/dune-stuff-demos.git src
  - cd src
  - git submodule update --init --recursive
  - cp config.opts/travis ~/travis.opts
  - echo removing modules ${MODULES_TO_DELETE}
  # ensures dune-stuff from travis own checkout is used
  - rm -rf ${MODULES_TO_DELETE} dune-stuff
  - ./dune-common/bin/dunecontrol --opts=~/travis.opts --module=dune-python configure
  - /home/travis/dune_build/dune-python/python2-env/bin/pip install -U pip
  - /home/travis/dune_build/dune-python/python3-env/bin/pip install -U pip
  - /home/travis/dune_build/dune-python/python2-env/bin/pip install -U distribute six
  - /home/travis/dune_build/dune-python/python3-env/bin/pip install -U distribute six
  - ./dune-common/bin/dunecontrol --opts=~/travis.opts all

# command to install dependencies
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - cd $HOME/src
  - ./dune-common/bin/dunecontrol --opts=config.opts/travis make install > /dev/null
  - rm -rf ~/{dune_build,src}

# # command to run tests
script:
    - cd ${TRAVIS_BUILD_DIR}
    - ~/dune/bin/dunecontrol --opts=~/travis.opts --only=dune-stuff all
    - ~/dune/bin/dunecontrol --opts=~/travis.opts --only=dune-stuff bexec make test -k
    - ~/dune/bin/dunecontrol --opts=~/travis.opts --only=dune-stuff bexec make headercheck -k

notifications:
  email:
    on_success: change
    on_failure: change

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

before_cache:
  - rm -rf ~/build/dune-stuff

cache:
  directories:
    - $HOME/dune
    - $HOME/.ccache

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - os: osx

#env:
  #global:
    ##- CAMPFIRE_TOKEN=abc123
  #matrix:
    #- MODULES_TO_DELETE="dune-fem dune-pdelab dune-typetree dune-grid dune-istl dune-testtools"
    #- MODULES_TO_DELETE="dune-fem dune-pdelab dune-typetree"
    #- USE_ALL_MODULES_IN_SUPER_REPO
