# This file is part of the dune-stuff project:
#   https://github.com/wwu-numerik/dune-stuff
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2015)
#   Rene Milk       (2015)

sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources: &commonsources
    - boost-latest
    - george-edison55-precise-backports
    packages: &commonpackages
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - libboost1.55-all-dev
    - python-pip
    - libtbb-dev
    - ccache
    - libsuitesparse-dev
    - lcov
    - curl
    - ninja-build

before_install:
  - : ${OPTS_FILE:="config.opts/travis.ninja"}
  - : ${MAKE:="ninja"}
  - sudo -E apt-get install -y -q python-pip python3-pip
  - sudo -E pip3 install virtualenv cpp-coveralls
  - sudo -E pip install virtualenv cpp-coveralls
  - export PATH=/usr/lib/ccache:$PATH
  - export CXX=${CXX_COMPILER} CC=${COMPILER}
  - cd $HOME
  - test -d src || git clone --branch=testtools https://github.com/wwu-numerik/dune-stuff-demos.git src
  - cd $HOME/src
  - git submodule update --init --recursive
  - git submodule status
  - cp ${OPTS_FILE} $HOME/travis.opts
  - export DCTRL_ARG="--builddir=${DUNE_BUILD_DIR}  --opts=${HOME}/travis.opts"
  - ./local/bin/download_external_libraries.py
  - ./local/bin/build_external_libraries.py
  # ensures ${MY_MODULE} from travis own checkout is used
  - echo removing modules ${MODULES_TO_DELETE}
  - rm -rf ${MODULES_TO_DELETE} ${MY_MODULE}

# command to install dependencies
install:
  - cd $HOME/src
  #- export INST_DCTRL=$HOME/dune/bin/dunecontrol
  - export SRC_DCTRL=$PWD/dune-common/bin/dunecontrol
  - ${SRC_DCTRL} ${DCTRL_ARG} all
  # move my travis checkout into this source tree
  - mv ${TRAVIS_BUILD_DIR} .

before_script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} configure
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE}
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE} -k test_binaries

script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE} test
    - ${TRAVIS_BUILD_DIR}/scripts/upload_test_logs.bash
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE} headercheck -k
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE} install | grep -v "Installing"
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${MAKE} package_source

# runs independent of 'script' failure/success
after_script:
    # reset for ctest
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec make clean
    - export CTEST_ARG="--output-on-failure -S ${TRAVIS_BUILD_DIR}/.travis.ctest"
    # ctest errors on coverage gathering, this should NOT fail our entire build
    #- ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ctest ${CTEST_ARG} || echo "CTest Failed"

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - MY_MODULE=dune-stuff DUNE_BUILD_DIR=${HOME}/dune_build/ INSTALL_DIR=$HOME/dune MAKE="make -j2"

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources:
          - *commonsources
          - 'ubuntu-toolchain-r-test'
          packages:
          - *commonpackages
          - ['g++-4.9', 'gcc-4.9']
      env: CXX_COMPILER=g++-4.9 COMPILER=gcc-4.9
    - os: linux
      compiler: gcc
      addons: *gcc49
      env: CXX_COMPILER=g++-4.9 COMPILER=gcc-4.9 MODULES_TO_DELETE="dune-fem dune-pdelab dune-typetree dune-grid dune-istl"
    - os: linux
      compiler: gcc
      addons: *gcc49
      env: CXX_COMPILER=g++-4.9 COMPILER=gcc-4.9 MODULES_TO_DELETE="dune-fem dune-pdelab"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - *commonsources
          - 'ubuntu-toolchain-r-test'
          packages:
          - *commonpackages
          - ['g++-5', 'gcc-5']
      env: CXX_COMPILER=g++-5 COMPILER=gcc-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7']
      env: CXX_COMPILER=clang++-3.7 COMPILER=clang-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7']
      env: OPTS_FILE=config.opts/travis.make MAKE="make -j2" CXX_COMPILER=clang++-3.7 COMPILER=clang-3.7
      
    #- os: linux
      #compiler: clang
      #addons:
        #apt:
          #sources:
          #- *commonsources
          #- ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          #packages:
          #- *commonpackages
          #- ['clang-3.8']
      #env: CXX_COMPILER=clang++-3.8 COMPILER=clang-3.8
