# This file is part of the dune-xt-la project:
#   https://github.com/dune-community/dune-xt-la
# Copyright 2009-2018 dune-xt-la developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2016 - 2017)
#   Rene Milk       (2016 - 2018)
#   Tobias Leibner  (2016)
#
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)

sudo: required
dist: trusty
language: generic
services: docker

before_script:
    - export IMAGE="dunecommunity/${MY_MODULE}-testing_${DOCKER_TAG}:${TRAVIS_BRANCH}"
    # get image with fallback to master branch of the super repo
    - docker pull ${IMAGE} || export IMAGE="dunecommunity/${MY_MODULE}-testing_${DOCKER_TAG}:master" ; docker pull ${IMAGE}
    - export ENV_FILE=${HOME}/env
    - python3 ./.travis.make_env_file.py
    - export DOCKER_RUN="docker run --env-file ${ENV_FILE} -v ${TRAVIS_BUILD_DIR}:/root/src/${MY_MODULE} ${IMAGE}"

script:
    - ${DOCKER_RUN} /root/src/${MY_MODULE}/.travis.script.bash

# runs independent of 'script' failure/success
after_script:
    - ${DOCKER_RUN} /root/src/${MY_MODULE}/.travis.after_script.bash
    # output for simpler replicability
    - docker images ${IMAGE}
    - echo ${DOCKER_RUN}


notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

env:
  global:
    - MY_MODULE=dune-xt-la

matrix:
  include:
        - env: DOCKER_TAG=gcc_full TESTS=0
        - env: DOCKER_TAG=gcc_full TESTS=1
    
        - env: DOCKER_TAG=gcc_no_istl_no_disc TESTS=0
        - env: DOCKER_TAG=gcc_no_istl_no_disc TESTS=1
    
        - env: DOCKER_TAG=gcc_no_disc TESTS=0
        - env: DOCKER_TAG=gcc_no_disc TESTS=1
    
        - env: DOCKER_TAG=clang_full TESTS=0
        - env: DOCKER_TAG=clang_full TESTS=1
    