sudo: false
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - libboost1.55-all-dev
    - python-pip
    - python3-pip
    - libtbb-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cd $HOME
  - test -d src || git clone --branch=travis http://users.dune-project.org/repositories/projects/dune-stuff-demos.git src
  - cd src
  - git submodule update --init --recursive
  - rm -rf dune-{testtools,stuff}
  - ./dune-common/bin/dunecontrol --opts=config.opts/travis all

# command to install dependencies
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cd $HOME/src
  - ./dune-common/bin/dunecontrol --opts=config.opts/travis make install
  - rm -rf ~/{build,src}

# # command to run tests
script:
    - cd ~/wwu-numerik/
    - ~/dune/bin/dunecontrol --opts=~/src/config.opts/travis --only=dune-stuff all
    - ~/dune/bin/dunecontrol --opts=~/src/config.opts/travis --only=dune-stuff bexec make test -k
    - ~/dune/bin/dunecontrol --opts=~/src/config.opts/travis --only=dune-stuff bexec make headercheck -k

notifications:
  email: 
    on_success: change
    on_failure: change

#after_success:
#- coveralls

branches:
  except:
    - gh-pages

before_cache:
  - rm -rf ~/build/dune-stuff

cache:
  directories:
    - $HOME/dune

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
