# ~~~
# This file is part of the dune-xt-la project:
#   https://github.com/dune-community/dune-xt-la
# Copyright 2009-2018 dune-xt-la developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2016 - 2017)
#   René Fritze     (2017 - 2018)
#   Tobias Leibner  (2018)
# ~~~

Module: dune-xt-la
Version: 18.11-dev
Maintainer: dune-xt-dev@listserv.uni-muenster.de
Depends: dune-testtools (>= 2.5) dune-xt-common (>= 18.11) dune-istl (>= 2.5)
