# ~~~
# This file is part of the dune-xt project:
#   https://github.com/dune-community/dune-xt
# Copyright 2009-2020 dune-xt developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2012 - 2014, 2016 - 2017, 2019)
#   René Fritze     (2009, 2011 - 2015, 2017 - 2019)
#   Tobias Leibner  (2015, 2018 - 2020)
# ~~~

Module: dune-xt
Version: 2022.1.1
Maintainer: dune-xt-dev@listserv.uni-muenster.de
Depends: dune-common (>= 2.6) dune-geometry (>= 2.6) dune-grid (>= 2.6) dune-istl (>= 2.6)
Suggests: dune-testtools (>= 2.6) dune-alugrid (>= 2.6) dune-grid-glue (>= 2.6) dune-uggrid (>= 2.6) dune-xt-data (>= 18.11)
